try job.if

diff --git a/.github/workflows/Ultica_ci_build.yml b/.github/workflows/Ultica_ci_build.yml
--- a/.github/workflows/Ultica_ci_build.yml
+++ b/.github/workflows/Ultica_ci_build.yml
@@ -60,20 +60,17 @@ jobs:
 
       - name: Compare IDs
         id: compare
+        if: github.base_ref
         run: |
-          if [[ -n "${{ github.base_ref }}" ]]; then  # github.base_ref is only set for PRs
-
-            echo "Switching to the target branch to get differences between ID lists"
-            git fetch --depth=1 origin +${{ github.base_ref }}
-            git checkout origin/${{ github.base_ref }}
-            mkdir "$BUILD_DIR/base_json/"
-            python3 "$BUILD_DIR/compose.py" $COMPOSE_ARGS --only-json "gfx/$TILESET" "$BUILD_DIR/base_json/"
-            wget -q -P "$BUILD_DIR" https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/list_tileset_ids.py \
-            || echo "Error: Failed to get list_tileset_ids.py"
-            echo -e "\nDifferences in IDs:"
-            (diff -u0 <(python3 "$BUILD_DIR/list_tileset_ids.py" "$BUILD_DIR/base_json/") <(python3 "$BUILD_DIR/list_tileset_ids.py" "$BUILD_DIR/")) | tail -n +3
-
-          fi
+          echo "Switching to the target branch to get differences between ID lists"
+          git fetch --depth=1 origin +${{ github.base_ref }}
+          git checkout origin/${{ github.base_ref }}
+          mkdir "$BUILD_DIR/base_json/"
+          python3 "$BUILD_DIR/compose.py" $COMPOSE_ARGS --only-json "gfx/$TILESET" "$BUILD_DIR/base_json/"
+          wget -q -P "$BUILD_DIR" https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/list_tileset_ids.py \
+          || echo "Error: Failed to get list_tileset_ids.py"
+          echo -e "\nDifferences in IDs:"
+          (diff -u0 <(python3 "$BUILD_DIR/list_tileset_ids.py" "$BUILD_DIR/base_json/") <(python3 "$BUILD_DIR/list_tileset_ids.py" "$BUILD_DIR/")) | tail -n +3
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v2
